package com.grocery.app.tabswipe.communicate;

import com.grocery.app.tabswipe.models.DataModel;

import java.util.List;
import retrofit.Callback;
import retrofit.http.GET;
import retrofit.http.Header;
import retrofit.http.Path;

// This interface doesn't have a regular implementation! Instead the
// implementation is generated by Retrofit.
public interface JsonService {

    @GET("/")
    public void getSomeContent(Callback<List<DataModel>> d);

}